### ISSUE TITLE
サンプルスライドページのmarkdownが崩れています

### ISSUE THREAD

**Issue by takiy33** [rabbit-shocker/rabbit#103]
いつもLTをやる時に使わせて頂いています 😋 

次のリンクで示すサンプルスライドページのmarkdownが崩れています。

[サンプルスライド](https://rabbit-shocker.org/ja/sample/markdown/rabbit.html)

お手すきの際に、修正して頂けると幸いです 🙏

**Comment by kou** [comment]
活用していてとてもすばらしいです！

修正しました！

**Comment by takiy33** [comment]
ありがとうございます 👍
