### ISSUE TITLE
初めてRabbitを試す時に早い段階で **動いた** の手応えがほしい

### ISSUE THREAD

**Issue by masayuki14** [rabbit-shocker/rabbit#104]
初めてRabbitを試す時に早い段階で **動いた** の手応えがほしいですが、
そこにたどり着くまでに1時間ほどかかってしまいました。
[rabbitコマンドの使い方](https://rabbit-shocker.org/ja/usage/rabbit.html) の
`% rabbit XXX.rd`の `XXX.rd`の簡単な中身があると、そのファイルを作ってすぐに動かしてスライドが表示できそうです。

たとえばこのような `XXX.rd` の例があると良いと思います。
```text
= 発表のタイトル

: author
   須藤功平
: institution
   COZMIXNG

= 1ページ目

ここは内容

= 2ページ目

おしまい
```

GitHubに[サンプルRD](https://raw.githubusercontent.com/rabbit-shocker/rabbit/master/sample/rabbit.rd)がありURL指定でコマンドが実行できるので

```
% rabbit https://raw.githubusercontent.com/rabbit-shocker/rabbit/master/sample/rabbit.rd
```

これも合わせて記載があるとより多くの情報がえられそうです。

**Comment by masayuki14** [comment]
これからRabbitを使ってスライド作っていきたいと思います。
素敵なプロダクトをありがとうございます！

**Comment by kou** [comment]
なるほど！
`XXX.rd`ではなく実際に動くものの方がよさそうですね！

pull requestにしてもらえますか！？

スライドの内容は↓くらいシンプルにしてもいいかもしれません！

```text
= タイトル

: author
   発表者名

= 1ページ目

ここは内容

= 2ページ目

おしまい
```

**Comment by masayuki14** [comment]
Pull Request 出します！

**Comment by kou** [comment]
さすがです！

**Comment by kou** [comment]
Done by #105
