### ISSUE TITLE
コマンドからPDFを出力すると画像サイズが指定通りに出力されない場合がある。

### ISSUE THREAD

**Issue by masayuki14** [rabbit-shocker/rabbit#107]
いつも楽しく使っています。ありがとうございます。
作成したスライドをPDFにしたくてコマンドラインから処理しましたところ
画像サイズが正しく出力されませんでした。

出力したPDFはこちらです。
https://github.com/masayuki14/reserve-docs/blob/master/slide/first-contact-oss-gate/OSS%20Gate%20%E3%81%AB%E5%8F%82%E5%8A%A0%E3%81%97%E3%81%A6%E3%81%8D%E3%81%9F.pdf

# 環境

- `% ruby -v` ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
- `% bundle -v` Bundler version 1.14.4
- `% bundle exec rabbit -v` 2.2.0
- OS X El Capitan 10.11.6（15G1217）

# 再現方法

使用したMarkdownはGitHubにあります。

```
% bundle exec rabbit -p 'https://raw.githubusercontent.com/masayuki14/reserve-docs/master/slide/first-contact-oss-gate/slide.md'
```

`OSS Gate に参加してきた.pdf` が出力されますが、画像サイズが指定通りではありません。

# 正常なケース

```
% bundle exec rabbit 'https://raw.githubusercontent.com/masayuki14/reserve-docs/master/slide/first-contact-oss-gate/slide.md'
```

スライドから出力する場合は正しく処理されました。

1. スライドで右クリック
1. メニューから **印刷** を選ぶ

**Comment by masayuki14** [comment]
ソースコードを見てみようと思いましたが、どこから手を付けたらいいかわからないのでアドバイスいただけると助かります。

**Comment by kou** [comment]
ちゃんと見ていないんですが、`height`とか`weight`とかではなくて`relative_height=90`とか`relative_weight=90`とかにしてみてください！

**Comment by masayuki14** [comment]
わかりました！

**Comment by kou** [comment]
たぶんうまく動いたはず！
