### ISSUE TITLE
OSX can not change to full screen size

### ISSUE THREAD

**Issue by tropicaljazz** [rabbit-shocker/rabbit#112]
OSX (10.13.3 High Sierra) で-fオプションで起動すると全画面で表示されるのですが、オプション無しの起動からF5あるいはメニューからフルスクリーンに変換しようとすると灰色の画面な表示され、全体が表示されません。。

<img width="1680" alt="2018-02-04 10 44 08" src="https://user-images.githubusercontent.com/107633/35773526-60cb5fde-0998-11e8-97bc-538350187c76.png">

環境は以下のとおりです

`ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]`
` rabbit -v 2.2.1`
`OS X High Sierra 10.13.3`

**Comment by kojix2** [comment]
同じ症状でますね
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
rabbit -v 2.2.1
OS X Sierra 10.12.6

**Comment by kou** [comment]
私に再現できる環境がないのでなんともできないんですよねぇ。。。

**Comment by kojix2** [comment]
https://twitter.com/ktou/status/910295037295988736
これはねぇ…気軽に提供できる金額じゃないですからね（苦笑）

**Comment by kou** [comment]
@kojix2 に再現できる環境を提供してもらってたしかに再現したので調べてみますね。

**Comment by kojix2** [comment]
ありがとうございます。

**Comment by kou** [comment]
次のリリースでバックエンドをgtk2 gemからgtk3 gemに切り替えるのですが、それでこの問題は解決します。

今年中にリリースしたいなぁ。。。

**Comment by tropicaljazz** [comment]
すみません。こちらをひさびさに見ました。
新しいマシンにインストールしたところ、この状況は起こりませんでした。
