### ISSUE TITLE
travis-ci doesn't run test

### ISSUE THREAD

**Issue by unasuke** [rabbit-shocker/rabbit#115]
latest commit in master branch is 5120b4cd582639a (2018-07-05) but latest build on travis-ci is 2018-02-27 .

https://travis-ci.org/rabbit-shocker/rabbit/builds/346609159

Why? 

## Note
I noticed that I ran test on HEAD (5120b4cd58) then it failed. `rake test` fails from the commit 4f98df6a804ca44 . @kou could you reproduce?

**Comment by kou** [comment]
I don't know why but this project is disabled on Travis CI.
I've enabled again.

**Comment by unasuke** [comment]
Thanks!
