### ISSUE TITLE
reload_theme key not handled in information window

### ISSUE THREAD

**Issue by martinetd** [rabbit-shocker/rabbit#118]
It looks like some keys do not work depending on which window has focus while the information window is up; for example I got this crash when reloading the theme and information window focused (it works fine with the main presentation window focused):

```
/src/rabbit/lib/rabbit/renderer/display/key-handler.rb:121:in `block in init_no_prefix_keys': undefined local variable or method `reload_theme' for #<Rabbit::InfoWindow:0x00005582e7b8ec90>
         from /usr/share/gems/gems/gobject-introspection-3.2.9/lib/gobject-introspection/loader.rb:587:in `invoke'
         from /usr/share/gems/gems/gobject-introspection-3.2.9/lib/gobject-introspection/loader.rb:587:in `block in define_method'
         from /src/rabbit/lib/rabbit/command/rabbit.rb:67:in `run'
         from /src/rabbit/lib/rabbit/command/rabbit.rb:29:in `run'
         from /src/rabbit/bin/rabbit:22:in `<main>'
/src/rabbit/bin/rabbit: [BUG] Segmentation fault at 0x0000003000000009
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

I'm sure it'd be easy to define reload_theme but I think it would be better to "forward" the key press to the correct context somehow, although I'm not too familiar with gtk nor ruby so that might be presumptuous of me to think that :)

**Comment by kou** [comment]
Thanks!
I've fixed.
