### ISSUE TITLE
ページ送りで表示が更新されない(macOS Mojave)

### ISSUE THREAD

**Issue by yoichi** [rabbit-shocker/rabbit#123]
macOS Mojave 環境で
```
$ rabbit scenario.rab
```
と起動して、SPCキーや→キーでページ送りしたときに、タイトルバーの文字列は更新されるのですが、
内容の表示が更新されません。

![image](https://user-images.githubusercontent.com/107537/54068356-3b0d6180-428f-11e9-8be8-8dec7cfd8756.png)

上のスクリーンショットで使っているスライドは
https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.rab
です。タイトルバーの表示と内容がずれています。

補足情報

* ウィンドウのタイトルバーの緑ボタンをクリックして最大化した状態では発生しません。
* タイトルバーをドラッグしてウィンドウを移動すると内容の表示が更新されます。

環境

* rabbit 2.2.1 (gem で install)
* ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin17] (brew で install)
* macOS Mojave バージョン 10.14

**Comment by kou** [comment]
報告ありがとうございます。
masterでは直っている気がするので早くリリースしないと！という気持ちになりました！

**Comment by kou** [comment]
3.0.0では直っているはず！
