### ISSUE TITLE
Tortoise and hare not showing up despite --allotted-time

### ISSUE THREAD

**Issue by abartov** [rabbit-shocker/rabbit#138]
I'm trying Rabbit 3.0 with one of the sample files (lightning-talk), and am specifying --allotted-time 5m, but only the slides show up, without the tortoise and hare.  I see no error message on the console. 

What might be the reason?
(Using Ruby 3.0.1 on Ubuntu 21.04)

**Comment by kou** [comment]
We need to use the "image-slider-number" theme for hare and the "image-timer" theme for tortoise but the "lightning-talk" theme that is used by `sample/lightning-talk.rd` doesn't use them.

Some themes such as the "default" theme uses them. Could you try the following?

```bash
rabbit --allotted-time 5m --theme default sample/lightning-talk.rd
```

**Comment by abartov** [comment]
Thank you, this works!  I suggest clarifying that in the documentation, or adding it to the FAQ.

**Comment by kou** [comment]
https://github.com/rabbit-shocker/rabbit/blob/master/doc/en/faq.rd is the source of FAQ page.
Feel free to open a pull request for it. :-)
