### ISSUE TITLE
support faraday 2.0

### ISSUE THREAD

**Issue by pravi** [rabbit-shocker/rabbit#151]
When running tests with faraday 2.0 it fails with
....................................................................E
===============================================================================
Error: test_upload(TestSlideShare): Faraday::Error: :multipart is not 
registered on Faraday::Request

full log https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037963

This is because faraday-multipart is now a separate gem and not included in faraday from 2.0. Please update the dependency to use faraday ~> 2.0 and faraday-multipart.

**Comment by kou** [comment]
Ah, we no longer need Faraday on master because we dropped support for uploading a slide to SlideShare. (SlideShare stopped providing an API to upload a slide.)
See also: cc0067e1a8de39cab058a8db2fb22baba78b9d8a

I'll release a new version.

**Comment by kou** [comment]
I've released Rabbit 3.0.2.
