### ISSUE TITLE
Key combinations are finicky

### ISSUE THREAD

**Issue by kingdonb** [rabbit-shocker/rabbit#158]
I have been trying to nail down my presentation style and learn all the important key combinations, and I noticed that some key combinations do not respond 100% of the time or consistently. Actually just one. The timer reset-

> alt+t

This is the keyboard combo, and I find that pressing it I get 50/50/50 results. Sometimes it works, sometimes it sends my timer flag to the end of the timeline, and sometimes it doesn't respond at all.

The most consistent results seem to come from pressing:

> `alt+t` (wait) `t`

It seems to vary how much it's likely to work based on what key you press next and how soon you press it.

I don't know if there's anything to be done in Rabbit to fix this honestly, but it took me a bit of time to figure this out so I thought I'd write it down here. Hope this helps someone. Rabbit 3.0.3, MacOS Ventura with the `vte` gem enhancement installed.

**Comment by kou** [comment]
Thanks for your report.
I didn't notice this because I don't use the timer reset feature.
