### ISSUE TITLE
rake pdf で out of memory

### ISSUE THREAD

**Issue by znz** [rabbit-shocker/rabbit#166]
https://github.com/znz/rurema-2024-10 のスライドの PDF などをアップロードしようとしたのですが、 `rake pdf` が out of memory で終了してしまって、壊れた pdf しか作成できなくなっています。

```
% ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin23]
% rabbit --version
3.0.3
% rake pdf
mkdir -p pdf
...../3.3.5/lib/ruby/gems/3.3.0/gems/rabbit-3.0.3/lib/rabbit/renderer/printer.rb:90:in `finish': out of memory
```

ruby 3.3.4 で試してみたり、macOS 15.0.1 で発生しているので、別マシンの macOS 14.7 で試してみたりしましたが、同じように out of memory で正常な PDF が作成できませんでした。

**Comment by kou** [comment]
Homebrewのcairoを再インストールしてみてもらえますか？

手元のMac miniだと生成できましたが、ちょっと古そう。

```console
$ sw_vers
ProductName:		macOS
ProductVersion:		14.1.2
BuildVersion:		23B92
```

**Comment by kou** [comment]
_macOSをアップグレードしたら再現したのでlldbで眺めていたんですが、masterだと修正されている https://gitlab.freedesktop.org/cairo/cairo/-/issues/870 な気がします。

**Comment by kou** [comment]
cairo 1.18.4がリリースされるまでのworkaroundは次のとおりです。

```bash
brew uninstall --ignore-dependencies cairo
brew install --HEAD cairo
```
