### ISSUE TITLE
Difficult to go absolutely full screen on OSX

### ISSUE THREAD

**Issue by colindean** [rabbit-shocker/rabbit#36]
When I choose "full screen" from the slides' contextual menu, the window bars go away and the screen maximizes. However, it does not hide the system bar, nor the dock.

This may be a limitation of XQuartz. Looking into it more, but I'd really like for this to happen somehow.

**Comment by kou** [comment]
Rabbit 3.0.0 uses GTK+ 3. GTK+ 3 can choose the native  Quartz backend. So we don't need to use XQuartz anymore.
