### ISSUE TITLE
2.1.5 does not resize on fullscreen

### ISSUE THREAD

**Issue by mtasaka** [rabbit-shocker/rabbit#58]
With rabbit 2.1.5, when I try
```
$ rabbit ./sample/rabbit.rd
```
and then type <F5>, rabbit does not resize. With 2.1.4, it correctly resizes.

Using Fedora 21 x86_64

**Comment by kou** [comment]
Oh... I should fix it and release a new version soon...

**Comment by mtasaka** [comment]
2.1.6 is okay, thank you!

**Comment by kou** [comment]
Thanks for confirming it!
