### ISSUE TITLE
(('note:(12345)')) と書くと何も表示されない

### ISSUE THREAD

**Issue by tmtm** [rabbit-shocker/rabbit#70]
スライド中に `(('note:(12345)'))` と書くとスライド全体が何も表示されなくなります。

`(('note:12345'))` や `(('note:(12345a)'))` は問題ありません。note: の後に括弧があり、括弧の中が数字のみの場合におかしくなるようです。

**Comment by kou** [comment]
うーん、RD的に`(数値のみ)`がシンタックスエラーみたいなんですよねぇ。。。
`(('...'))`の中だからエスケープもできなそうだからどうしようかしら。。。

**Comment by kou** [comment]
あぁ、`(1)`みたいに順序付きリスト扱いだからか。

**Comment by tmtm** [comment]
RD の文法の問題だからしょうがないって感じですかねー。
であればクローズしてくださいませ…。

**Comment by kou** [comment]
しょうがないのでクローズします！
