### ISSUE TITLE
http://rabbit-shocker.org/ja/の画像とリンクが重なってリンクに飛べないページがある。

### ISSUE THREAD

**Issue by YU-TAYU** [rabbit-shocker/rabbit#75]
http://rabbit-shocker.org/ja/usage.html
上記のページでうさぎと亀の画像とリンクが重なっており、リンクに飛べないようになっているので、修正可能でしたらお願いします。
全体も一応確認しましたが、見たところ上記の概要のページだけだと思います。

**Comment by kou** [comment]
報告ありがとうございます！
修正可能なので直しました！
