### ISSUE TITLE
Markdown で書かれたスライド中の画像が、亀が動いた時に少し小さくなる

### ISSUE THREAD

**Issue by tmtm** [rabbit-shocker/rabbit#78]
たとえば、sample/rabbit.md を `rabbit --allotted-time=1m rabbit.md` のようにして表示し、15ページ目を表示しておくと、亀が動いたタイミングで画像が少し小さくなります。
メニューから Reload theme を選ぶと元の大きさに戻りますが、その後、亀が動くとまた小さくなります。

Cache all slides でキャッシュしても発生します。

rabbit.md では発生しますが、rabbit.rd では発生しないため、Markdown 固有の問題かもしれません。

**Comment by kou** [comment]
masterで直しておきました！

**Comment by tmtm** [comment]
直りました！ありがとうございます！
