### ISSUE TITLE
uninitialized constant Cairo::Color (NameError) Exception on Mac OS X

### ISSUE THREAD

**Issue by brettchalupa** [rabbit-shocker/rabbit#87]
Hi, I recently upgraded to OS X 10.11 (El Capitan), and rabbit throws an exception when running `rabbit path/to/slide.rb`. I am not 100% certain the OS X upgrade introduced the issue, but that was my first guess since rabbit was working before I upgraded.

Here is the full stack trace of the exception:

```
/Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant Cairo::Color (NameError)
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/gems/ruby-2.2.3/gems/rabbit-2.1.8/lib/rabbit/gtk.rb:23:in `<top (required)>'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/gems/ruby-2.2.3/gems/rabbit-2.1.8/lib/rabbit/logger/gui.rb:1:in `<top (required)>'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/gems/ruby-2.2.3/gems/rabbit-2.1.8/lib/rabbit/logger.rb:20:in `<top (required)>'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/gems/ruby-2.2.3/gems/rabbit-2.1.8/lib/rabbit/slide-configuration.rb:22:in `<top (required)>'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/gems/ruby-2.2.3/gems/rabbit-2.1.8/lib/rabbit/command/rabbit.rb:20:in `<top (required)>'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/brett/.rvm/gems/ruby-2.2.3/gems/rabbit-2.1.8/bin/rabbit:20:in `<top (required)>'
        from /Users/brett/.rvm/gems/ruby-2.2.3/bin/rabbit:23:in `load'
        from /Users/brett/.rvm/gems/ruby-2.2.3/bin/rabbit:23:in `<main>'
        from /Users/brett/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
        from /Users/brett/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Here is a detailed list of versions of software I am using:

- MRI ruby 2.2.3p173
- OS X 10.11.2
- cairo 1.14.4 (via homebrew)
- XQuartz 2.7.8

I followed the [Homebrew guide](https://github.com/rabbit-shocker/rabbit/blob/master/doc/en/install/homebrew.rd), and I have the ENV set for `DYLD_LIBRARY_PATH`.

Also, here is the slide file I am using for testing:

```
= Rabbit Test

: subtitle
  Testing Out Rabbit
: author
  Brett Chalupa
: allotted-time
  60 m

= Hi

This is a test slide.
```

Let me know if there is any other info I can provide, things I can try, or code I can write to try to help. I really appreciate rabbit and all the time that goes into it, so thank you! :smile:

**Comment by brettchalupa** [comment]
I realized that I had another computer with the previous version of OS X, 10.10.5, on it so I followed the Homebrew steps and still get the same error, which makes me think the the OS X upgrade was not the cause of the issue. I will keep debugging!

**Comment by kou** [comment]
Thanks for your report.
Could you upgrade your RubyGems by the following?

```text
% gem install rubygems-update
% update_rubygems
```

**Comment by brettchalupa** [comment]
@kou that totally fixed it, thank you very much! Would it be helpful if I add that step to https://github.com/rabbit-shocker/rabbit/blob/master/doc/en/install/homebrew.rd? I am happy to do so.

**Comment by kou** [comment]
Thanks for your suggestion.
Could you try Ruby 2.2.4 before doing it? 2.2.4 is the latest 2.2 series.

**Comment by brettchalupa** [comment]
@kou I tested the machine that did not have the rubygems update, updated to Ruby 2.2.4, and Rabbit worked as expected. Thank you very much, and I am sorry that I did not try that first. :sweat_smile:
