### ISSUE TITLE
全角空白を使うとスライドが文字化ける場合がある

### ISSUE THREAD

**Issue by taki3** [rabbit-shocker/rabbit#92]
全角空白を使うと文字化けることがあります。文字化けない場合もありますが、具体的な条件に切り分けられていません。
## 環境
- ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
- rabbit 2.1.9
- Mac OS X El Capitan バージョン 10.11.5
## 再現手順

`slide.md`に対して、`rabbit slide.md`を実行します。`slid`と`e`の間に全角空白を入れています。
また、文字コードは、UTF-8です。

```
# slid　e
```
## 文字化けた画面

実際に文字化けたスライドの画面です。

<img width="795" alt="2016-05-29 19 14 11" src="https://cloud.githubusercontent.com/assets/3800237/15632599/396d4b78-25d3-11e6-9154-2e0012c954ba.png">

**Comment by kou** [comment]
なんででしょうねぇ。
この四角の中に4つの数字がでるときは、フォントが見つからなくてUnicodeのコードポイントを出しているとき（全角スペースはU+3000）なんですが、フォントが見つかっていないんですかねぇ。cairoかPangoでアレなんですかねぇ。

**Comment by takiy33** [comment]
4つの数字は、Unicodeのコードポイントを表しているのですね。(知らなかったです)
時間がある時に、もう少し調べてみます
