### ISSUE TITLE
Does not run on Japanese Windows 10

### ISSUE THREAD

**Issue by dogatana** [rabbit-shocker/rabbit#93]
Hi,

I tried to start using rabbit on Windows 10, but failed.
Did I miss something?

### First Try
```
toshi@TOSHI-PC C:\Programs\ruby\lib\ruby\gems\2.3.0\gems\rabbit-2.1.9\sample
> rabbit rabbit.md
[エラー]
Encoding::InvalidByteSequenceError: "\xFF" on Windows-31J
C:/Programs/ruby/lib/ruby/gems/2.3.0/gems/rabbit-2.1.9/lib/rabbit/image/pdf.rb:18:in `gets' C:/Programs/ruby/lib/ruby/gems/2.3.0/gems/rabbit-2.1.9/lib/rabbit/image/pdf.rb:18:in `block in match?'
C:/Programs/ruby/lib/ruby/gems/2.3.0/gems/rabbit-2.1.9/lib/rabbit/image/pdf.rb:17:in `open' C:/Programs/ruby/lib/ruby/gems/2.3.0/gems/rabbit-2.1.9/lib/rabbit/image/pdf.rb:17:in `match?'
...
```

### Modify rabbit.bat
After this, I changed rabbit.bat as follows.

```
--- rabbit.bat.orig     Sun Jul 10 10:58:41 2016
+++ rabbit.bat  Sun Jul 10 11:01:19 2016
@@ -3,4 +3,4 @@
 @"C:\Programs\ruby\bin\ruby.exe" "C:/Programs/ruby/bin/rabbit" %1 %2 %3 %4 %5 %6 %7 %8 %9
 GOTO :EOF
 :WinNT
-@"C:\Programs\ruby\bin\ruby.exe" "%~dpn0" %*
+@"C:\Programs\ruby\bin\ruby.exe" --external-encoding=utf-8 "%~dpn0" %*
```

### Second Try

```
toshi@TOSHI-PC C:\Programs\ruby\lib\ruby\gems\2.3.0\gems\rabbit-2.1.9\sample
> rabbit rabbit.md
[エラー]
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
C:/Programs/ruby/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
C:/Programs/ruby/lib/ruby/2.3.0/net/http.rb:933:in `connect'
...
```

### My Environment
- Windows 10 Pro
- ruby 2.3.0p0 (2015-12-25 revision 53290) [i386-mingw32]

**Comment by kou** [comment]
Thanks for your report.

I've fixed the first `Encoding::InvalidByteSequenceError` problem at master. It'll be fixed in the next release. Adding `--external-encoding=utf-8` is a reasonable workaround until the next release is released.

The second `OpenSSL::SSL:SSLError` isn't Rabbit's problem. Try https://gist.github.com/luislavena/f064211759ee0f806c88 .

**Comment by dogatana** [comment]
Hi,
Thank you for the information.
I tried the way to fix SSL error manually, but could not fix.
The reason is that I have already the specified pem file in the rubygems folder.

I gave up..

**Comment by kou** [comment]
Could you show full message?

And could you try `samples/pre.rd` instead?

**Comment by dogatana** [comment]
Hi,
Sorry for late response.
I attache a file.
[log.txt](https://github.com/rabbit-shocker/rabbit/files/391415/log.txt)

samples/pre.rd worked fine.
Rabbit showed one warning, though.

> rabbit pre.rd                
[警告]                           
enscript: サポートしていない言語です: c

**Comment by kou** [comment]
Thanks.
How about using "方法６" in http://mofuken.blogspot.jp/2012/12/ruby-open-uri-https-certificate-verify.html ?

You don't need to care the `enscript` warning. Because normally enscript isn't installed on Windows.

**Comment by dogatana** [comment]
Hi,

Finally, "方法６" worked well.
Now I can use rabbit.

Many Thanks!!

**Comment by kou** [comment]
Good.
