### ISSUE TITLE
rabbit-slide new で markdown のときにタイトルページの生成がおかしい

### ISSUE THREAD

**Issue by znz** [rabbit-shocker/rabbit#95]
`rabbit-slide new --id test-slide --base-name example --markup-language=markdown --title="テストスライド" --tags=ruby --allotted-time=30m --presentation-date=2016-10-09 --name "Foo Bar"` のように生成すると

```markdown
# テストスライド

author
:   Foo Bar
date
:   2016-10-09
allotted-time
:   30m
```

のようになっていて、

<img width="912" alt="2016-10-09 15 37 01" src="https://cloud.githubusercontent.com/assets/11857/19218502/691ecaf6-8e36-11e6-9ff9-5fb394900614.png">

のように author や date が表示されません。

```markdown
# テストスライド

author
:   Foo Bar

date
:   2016-10-09

allotted-time
:   30m
```

のように改行を入れると

<img width="912" alt="2016-10-09 15 39 26" src="https://cloud.githubusercontent.com/assets/11857/19218508/9e150842-8e36-11e6-989d-7ec25efe7442.png">

のようにちゃんと表示されるようになるので、`rabbit-slide new` の生成部分の問題ではないでしょうか。

**Comment by kou** [comment]
その通りなので直しました！
