### ISSUE TITLE
typo in repository description

### ISSUE THREAD

**Issue by znz** [rabbit-shocker/rabbit#96]
https://github.com/rabbit-shocker/rabbit に「A programable presentaton tool by Ruby.」とありますが、programmable presentation の typo ではないでしょうか。

**Comment by kou** [comment]
どっちでもいいらしいのですがmmの方が多く使われているようなのでmmにしました。

**Comment by znz** [comment]
presentaton のままのようです。

**Comment by kou** [comment]
直しました。2つあるなら2つあると言ってもらえるととても助かりました。
