### ISSUE TITLE
Windowsでフルスクリーンのトグルができない　

### ISSUE THREAD

**Issue by tdtds** [rabbit-shocker/rabbit#98]
WindowsでF11キーを使ってフルスクリーンにした状態で、もう一度F11を押してもフルスクリーン状態がキャンセルされない。フルスクリーン状態のままだと他のウィンドウをフォアグラウンドにできなくて不便です。

`gem install rabbit` でインストールしたRabbit 2.1.9です。

```
C:\> rabbit --version
2.1.9
C:\> ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]
```

OSはWindows 7 Professional SP1 64bit。他のOSで同じ現象が起きるかどうかは確認していません。

実行すると以下のエラーが出ていますが、フルスクリーン操作とは無関係に出ているように見えます。

```
C:\>rabbit note.rab
C:/usr/ruby/lib/ruby/gems/2.3.0/gems/rabbit-2.1.9/lib/rabbit/image-data-loader.rb:30:in `load': 'Gdk::PixbufLoader' has been deprecated. Use
 'GdkPixbuf::PixbufLoader'.
C:/usr/ruby/lib/ruby/gems/2.3.0/gems/rabbit-2.1.9/lib/rabbit/image-data-loader.rb:37:in `rescue in load': 'Gdk::PixbufError' has been deprec
ated. Use 'GdkPixbuf::PixbufError'.
```

**Comment by yoku0825** [comment]
わたしの環境（Windows 10）でも同じ現象が起きます。

```
C:\>rabbit --version
2.1.9

C:\>systeminfo
..
OS 名:                  Microsoft Windows 10 Home
OS バージョン:          10.0.14393 N/A ビルド 14393
```

何か提供できる情報があれば教えてください。
（Rabbitじゃなくて使っているGUIライブラリーの気がします）

**Comment by kou** [comment]
あとで試してみますが、昔、フルスクリーンにしようとしてもならなかった環境用に入れたフォールバックのフルスクリーン処理が動いてしまってこうなっているのかなぁという気がしています。

`GdkPixbuf`の警告は今のmasterでは直っているので次のリリースではなくなるはずです。

**Comment by kou** [comment]
直したので次のリリースからは効くようになります。
